version: "3.7"
services:
  flask:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 CFT:app
    environment:
      - FLASK_APP=CFT.py
    ports:
      - 5000:5000
    volumes:
      - ./:/opt/app